import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/loginone">LoginOne</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/managefootageone">ManageFootageOne</Link>
        </li>
        <li>
          <Link to="/settingsone">SettingsOne</Link>
        </li>
        <li>
          <Link to="/settingstwo">SettingsTwo</Link>
        </li>
        <li>
          <Link to="/manageaffiliate">ManageAffiliate</Link>
        </li>

        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/managefootage">ManageFootage</Link>
        </li>
        <li>
          <Link to="/reviewrequest">ReviewRequest</Link>
        </li>
        <li>
          <Link to="/reviewrequesttwo">ReviewRequestTwo</Link>
        </li>
        <li>
          <Link to="/affiliateperformance">Affiliateperformance</Link>
        </li>
        <li>
          <Link to="/reviewrequestthree">ReviewRequestThree</Link>
        </li>
        <li>
          <Link to="/manageaffiliateone">ManageAffiliateOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
